# docker-composeのバージョン指定
version: '3.8'
services:
  nginx:
    container_name: curriculum-nginx
    image: nginx:latest
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d:cached
      - ./app:/var/www/html:cached
      # 静的ファイルは別ボリュームで高速化
      - app_vendor:/var/www/html/vendor
      - app_node_modules:/var/www/html/node_modules
    ports:
      - "80:80"
    depends_on:
      - php
      - echo-server

  php:
    container_name: curriculum-laravel
    ###############################################################
    # Mac M1チップユーザーは以下のコメントアウトを解除して作業を進めてください
    # platform: linux/x86_64
    ###############################################################
    build:
      context: ./
      dockerfile: docker/php/Dockerfile
    volumes:
      # メインのアプリケーションコード（cached で高速化）
      - ./app:/var/www/html:cached
      # 重いディレクトリは別ボリュームに分離
      - app_vendor:/var/www/html/vendor
      - app_node_modules:/var/www/html/node_modules
      # 一時ファイルとキャッシュも分離
      - app_storage:/var/www/html/storage
      - app_bootstrap_cache:/var/www/html/bootstrap/cache
      # 設定ファイル
      - ./docker/php/check_startup.sh:/tmp/check_startup.sh:cached
      - ./docker/php/conf/custom.ini:/usr/local/etc/php/conf.d/custom.ini:cached
    expose:
      - "9000"
    depends_on:
      - db
      - redis
    environment:
      PHP_INI_SET: "display_errors=Off"
      REDIS_HOST: redis
      REDIS_PORT: 6379
      # --- ここを修正 ---
      BROADCAST_DRIVER: redis
      # Laravel Echo Server (ローカル) の認証設定
      # ここで設定する PUSHER_APP_KEY は laravel-echo-server.json と同じ値にすること
      PUSHER_APP_KEY: ${APP_KEY} # ホストの .env の APP_KEY を使う
      PUSHER_APP_ID: some_id # 必要に応じて任意のID (laravel-echo-serverでは重要ではないがLaravel側で必要)
      PUSHER_APP_SECRET: some_secret # 必要に応じて任意のシークレット (laravel-echo-serverでは重要ではないがLaravel側で必要)
      PUSHER_HOST: echo-server # LaravelがEcho Serverにイベントを送る際のホスト名（Docker内部のサービス名）
      PUSHER_PORT: 6001
      PUSHER_SCHEME: http
      # JavaScriptに渡すEchoの設定
      MIX_PUSHER_APP_KEY: ${APP_KEY} # Laravel Mix でビルドする app.js に埋め込むキー
      VITE_PUSHER_APP_KEY: ${APP_KEY} # Vite でビルドする app.js に埋め込むキー
      # --- 修正ここまで ---
      APP_KEY: ${APP_KEY}

  db:
    container_name: curriculum-db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: 'Asia/Tokyo'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306

  phpMyAdmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_PARBIRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root
    links:
      - db
    ports:
      - 4040:80
    volumes:
      - phpmyadmin_sessions:/sessions

  # Redis サービス (そのまま)
  redis:
    container_name: curriculum-redis
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

  # Laravel Echo Server サービス
  echo-server:
    container_name: curriculum-echo-server
    build:
      context: .
      dockerfile: docker/echo-server/Dockerfile
    # --- ここを修正 ---
    command: laravel-echo-server start --no-daemon --force --debug --host=0.0.0.0 --port=6001 --authHost=http://nginx:80 --redisHost=redis --redisPort=6379 --config=/var/www/html/laravel-echo-server.json
    volumes:
      - ./app:/var/www/html:cached
      - app_node_modules:/var/www/html/node_modules
    # --- 修正ここまで ---
    ports:
      - "6001:6001"
    environment:
      AUTH_HOST: http://nginx:80
      APP_KEY: ${APP_KEY} # laravel-echo-server.json の ${APP_KEY} に渡される
      REDIS_HOST: redis # Redisサービス名をホストとして指定
      REDIS_PORT: 6379  # Redisのデフォルトポート
    depends_on:
      - php
      - redis

volumes:
  db_data:
  redis_data:
  # 新しく追加したボリューム
  app_vendor:
  app_node_modules:
  app_storage:
  app_bootstrap_cache:
  phpmyadmin_sessions: